// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingManagement.DAL.Data;

#nullable disable

namespace ParkingManagement.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingManagement.DAL.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = "ACC001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tung.ql@baixetranphu.vn",
                            IsActive = true,
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMaJnFd1jC9s5sJq1bKx5HY4i6",
                            RequirePasswordChange = false,
                            Role = "Manager",
                            Username = "nguyen.thanh.tung"
                        },
                        new
                        {
                            AccountId = "ACC002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mai.nv@baixetranphu.vn",
                            IsActive = true,
                            PasswordHash = "$2a$12$XpV8cBnqRT5HaK2dLM7OiuZqY1P4sNwFhG9rU3vKj6mE0eXcQl8n2",
                            RequirePasswordChange = false,
                            Role = "Employee",
                            Username = "tran.thi.mai"
                        },
                        new
                        {
                            AccountId = "ACC003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hung.nv@baixetranphu.vn",
                            IsActive = true,
                            PasswordHash = "$2a$12$XpV8cBnqRT5HaK2dLM7OiuZqY1P4sNwFhG9rU3vKj6mE0eXcQl8n2",
                            RequirePasswordChange = false,
                            Role = "Employee",
                            Username = "le.van.hung"
                        },
                        new
                        {
                            AccountId = "ACC004",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "baopq@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$12$9kM4pJ3wC8zN2vR7xF5qEuY6tL0sG1hB4dI8nK3oS2aA7cW9mP1y0",
                            RequirePasswordChange = false,
                            Role = "Customer",
                            Username = "pham.quoc.bao"
                        },
                        new
                        {
                            AccountId = "ACC005",
                            CreatedAt = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lanhothuy@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$12$9kM4pJ3wC8zN2vR7xF5qEuY6tL0sG1hB4dI8nK3oS2aA7cW9mP1y0",
                            RequirePasswordChange = false,
                            Role = "Customer",
                            Username = "ho.thi.lan"
                        },
                        new
                        {
                            AccountId = "ACC006",
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khoaRacing2001@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$12$9kM4pJ3wC8zN2vR7xF5qEuY6tL0sG1hB4dI8nK3oS2aA7cW9mP1y0",
                            RequirePasswordChange = false,
                            Role = "Customer",
                            Username = "dang.minh.khoa"
                        },
                        new
                        {
                            AccountId = "ACC007",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thuhuong.ntn@yahoo.com",
                            IsActive = true,
                            PasswordHash = "$2a$12$9kM4pJ3wC8zN2vR7xF5qEuY6tL0sG1hB4dI8nK3oS2aA7cW9mP1y0",
                            RequirePasswordChange = false,
                            Role = "Customer",
                            Username = "nguyen.thu.huong"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = "CUS001",
                            AccountId = "ACC004",
                            FullName = "Phạm Quốc Bảo",
                            Gender = "Male",
                            IsDeleted = false,
                            PhoneNumber = "0931122334"
                        },
                        new
                        {
                            CustomerId = "CUS002",
                            AccountId = "ACC005",
                            FullName = "Hồ Thị Lan",
                            Gender = "Female",
                            IsDeleted = false,
                            PhoneNumber = "0942233445"
                        },
                        new
                        {
                            CustomerId = "CUS003",
                            AccountId = "ACC006",
                            FullName = "Đặng Minh Khoa",
                            Gender = "Male",
                            IsDeleted = false,
                            PhoneNumber = "0953344556"
                        },
                        new
                        {
                            CustomerId = "CUS004",
                            AccountId = "ACC007",
                            FullName = "Nguyễn Thị Thu Hương",
                            Gender = "Female",
                            IsDeleted = false,
                            PhoneNumber = "0964455667"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Shift")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = "EMP001",
                            AccountId = "ACC002",
                            EmployeeCode = "EMP001",
                            FullName = "Trần Thị Mai",
                            Gender = "Female",
                            IsDeleted = false,
                            ManagerId = "MGR001",
                            PhoneNumber = "0912345678",
                            Shift = "Sáng"
                        },
                        new
                        {
                            EmployeeId = "EMP002",
                            AccountId = "ACC003",
                            EmployeeCode = "EMP002",
                            FullName = "Lê Văn Hùng",
                            Gender = "Male",
                            IsDeleted = false,
                            ManagerId = "MGR001",
                            PhoneNumber = "0923456789",
                            Shift = "Chiều"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.EmployeeInvite", b =>
                {
                    b.Property<string>("InviteToken")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Shift")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InviteToken");

                    b.ToTable("EmployeeInvites");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Manager", b =>
                {
                    b.Property<string>("ManagerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ManagerId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            ManagerId = "MGR001",
                            AccountId = "ACC001",
                            FullName = "Nguyễn Thành Tùng",
                            Gender = "Male",
                            IsDeleted = false,
                            PhoneNumber = "0901234567"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.MonthlyTicket", b =>
                {
                    b.Property<string>("MonthlyTicketId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(10,0)");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MonthlyTicketId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehiclePlate");

                    b.ToTable("MonthlyTickets", t =>
                        {
                            t.HasCheckConstraint("CK_MonthlyTicket_Status", "Status IN (N'Hoạt động', N'Hết hạn', N'Đã hủy')");
                        });

                    b.HasData(
                        new
                        {
                            MonthlyTicketId = "MTK001",
                            CreatedAt = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS004",
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageType = "1 tháng",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Hoạt động",
                            TotalFee = 350000m,
                            VehiclePlate = "43D-234.56",
                            VehicleType = "Ô tô lớn"
                        },
                        new
                        {
                            MonthlyTicketId = "MTK002",
                            CreatedAt = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS001",
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageType = "3 tháng",
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Hoạt động",
                            TotalFee = 650000m,
                            VehiclePlate = "51G-888.88",
                            VehicleType = "Ô tô nhỏ"
                        },
                        new
                        {
                            MonthlyTicketId = "MTK003",
                            CreatedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS003",
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PackageType = "1 tháng",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Hết hạn",
                            TotalFee = 150000m,
                            VehiclePlate = "43C-789.01",
                            VehicleType = "Xe máy"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Otp", b =>
                {
                    b.Property<string>("OtpId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OtpId");

                    b.HasIndex("Email");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.ParkingSlot", b =>
                {
                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SlotId");

                    b.ToTable("ParkingSlots", t =>
                        {
                            t.HasCheckConstraint("CK_ParkingSlot_Status", "Status IN (N'Trống', N'Đang sử dụng', N'Đã đặt', N'Bảo trì')");
                        });

                    b.HasData(
                        new
                        {
                            SlotId = "A01",
                            LastUpdated = new DateTime(2026, 5, 10, 8, 23, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu A - Ô 01",
                            Status = "Đang sử dụng",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            SlotId = "A02",
                            LastUpdated = new DateTime(2026, 5, 9, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu A - Ô 02",
                            Status = "Trống",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            SlotId = "A03",
                            LastUpdated = new DateTime(2026, 5, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu A - Ô 03",
                            Status = "Trống",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            SlotId = "A04",
                            LastUpdated = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu A - Ô 04",
                            Status = "Đã đặt",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            SlotId = "A05",
                            LastUpdated = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu A - Ô 05",
                            Status = "Trống",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            SlotId = "B01",
                            LastUpdated = new DateTime(2026, 5, 10, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu B - Ô 01",
                            Status = "Đang sử dụng",
                            VehicleType = "Ô tô nhỏ"
                        },
                        new
                        {
                            SlotId = "B02",
                            LastUpdated = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu B - Ô 02",
                            Status = "Trống",
                            VehicleType = "Ô tô nhỏ"
                        },
                        new
                        {
                            SlotId = "B03",
                            LastUpdated = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu B - Ô 03",
                            Status = "Trống",
                            VehicleType = "Ô tô nhỏ"
                        },
                        new
                        {
                            SlotId = "C01",
                            LastUpdated = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu C - Ô 01",
                            Status = "Đang sử dụng",
                            VehicleType = "Ô tô lớn"
                        },
                        new
                        {
                            SlotId = "C02",
                            LastUpdated = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Khu C - Ô 02",
                            Status = "Trống",
                            VehicleType = "Ô tô lớn"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.ParkingSlotAuditLog", b =>
                {
                    b.Property<string>("LogId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LogId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SlotId");

                    b.ToTable("ParkingSlotAuditLogs");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,0)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MonthlyTicketId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentId");

                    b.HasIndex("MonthlyTicketId")
                        .IsUnique()
                        .HasFilter("[MonthlyTicketId] IS NOT NULL");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasFilter("[TicketId] IS NOT NULL");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_TicketOrMonthly", "(TicketId IS NOT NULL AND MonthlyTicketId IS NULL) OR (TicketId IS NULL AND MonthlyTicketId IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            PaymentId = "PAY001",
                            Amount = 10500m,
                            Method = "Tiền mặt",
                            PaymentTime = new DateTime(2026, 5, 9, 17, 31, 0, 0, DateTimeKind.Unspecified),
                            Status = "Thành công",
                            TicketId = "TKT004"
                        },
                        new
                        {
                            PaymentId = "PAY002",
                            Amount = 13500m,
                            Method = "Chuyển khoản",
                            PaymentTime = new DateTime(2026, 5, 8, 12, 1, 0, 0, DateTimeKind.Unspecified),
                            Status = "Thành công",
                            TicketId = "TKT005"
                        },
                        new
                        {
                            PaymentId = "PAY003",
                            Amount = 24000m,
                            Method = "Tiền mặt",
                            PaymentTime = new DateTime(2026, 5, 7, 11, 1, 0, 0, DateTimeKind.Unspecified),
                            Status = "Thành công",
                            TicketId = "TKT006"
                        },
                        new
                        {
                            PaymentId = "PAY004",
                            Amount = 24000m,
                            Method = "Tiền mặt",
                            PaymentTime = new DateTime(2026, 5, 9, 12, 31, 0, 0, DateTimeKind.Unspecified),
                            Status = "Thành công",
                            TicketId = "TKT007"
                        },
                        new
                        {
                            PaymentId = "PAY005",
                            Amount = 350000m,
                            Method = "Ví điện tử",
                            MonthlyTicketId = "MTK001",
                            PaymentTime = new DateTime(2026, 5, 1, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            Status = "Thành công"
                        },
                        new
                        {
                            PaymentId = "PAY006",
                            Amount = 650000m,
                            Method = "Chuyển khoản",
                            MonthlyTicketId = "MTK002",
                            PaymentTime = new DateTime(2026, 4, 1, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            Status = "Thành công"
                        },
                        new
                        {
                            PaymentId = "PAY007",
                            Amount = 150000m,
                            Method = "Tiền mặt",
                            MonthlyTicketId = "MTK003",
                            PaymentTime = new DateTime(2026, 3, 1, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            Status = "Thành công"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.PricingConfiguration", b =>
                {
                    b.Property<string>("PricingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PricingId");

                    b.ToTable("PricingConfigurations");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Reservation", b =>
                {
                    b.Property<string>("ReservationId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExpectedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SlotId");

                    b.HasIndex("VehiclePlate");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_Status", "Status IN (N'Chờ', N'Đã nhận', N'Hủy', N'Hết hạn')");
                        });

                    b.HasData(
                        new
                        {
                            ReservationId = "RES001",
                            CreatedAt = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS003",
                            ExpectedTime = new DateTime(2026, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotId = "A04",
                            Status = "Chờ",
                            VehiclePlate = "43C-789.01"
                        },
                        new
                        {
                            ReservationId = "RES002",
                            CreatedAt = new DateTime(2026, 5, 7, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS002",
                            ExpectedTime = new DateTime(2026, 5, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotId = "B03",
                            Status = "Đã nhận",
                            VehiclePlate = "43B-456.78"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(10,0)");

                    b.Property<string>("SlotId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TicketId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SlotId");

                    b.HasIndex("VehiclePlate");

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("CK_Ticket_Status", "Status IN (N'Đang trong bãi', N'Đã ra')");
                        });

                    b.HasData(
                        new
                        {
                            TicketId = "TKT001",
                            CheckInTime = new DateTime(2026, 5, 10, 8, 23, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS001",
                            Fee = 0m,
                            SlotId = "A01",
                            Status = "Đang trong bãi",
                            VehiclePlate = "43A-123.45",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            TicketId = "TKT002",
                            CheckInTime = new DateTime(2026, 5, 10, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS002",
                            Fee = 0m,
                            SlotId = "B01",
                            Status = "Đang trong bãi",
                            VehiclePlate = "43B-456.78",
                            VehicleType = "Ô tô nhỏ"
                        },
                        new
                        {
                            TicketId = "TKT003",
                            CheckInTime = new DateTime(2026, 5, 10, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Fee = 0m,
                            SlotId = "A05",
                            Status = "Đang trong bãi",
                            VehiclePlate = "92C-111.22",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            TicketId = "TKT004",
                            CheckInTime = new DateTime(2026, 5, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2026, 5, 9, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS003",
                            Fee = 10500m,
                            SlotId = "A02",
                            Status = "Đã ra",
                            VehiclePlate = "43C-789.01",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            TicketId = "TKT005",
                            CheckInTime = new DateTime(2026, 5, 8, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2026, 5, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS001",
                            Fee = 13500m,
                            SlotId = "A03",
                            Status = "Đã ra",
                            VehiclePlate = "43A-123.45",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            TicketId = "TKT006",
                            CheckInTime = new DateTime(2026, 5, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2026, 5, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = "CUS002",
                            Fee = 24000m,
                            SlotId = "B02",
                            Status = "Đã ra",
                            VehiclePlate = "43B-456.78",
                            VehicleType = "Ô tô nhỏ"
                        },
                        new
                        {
                            TicketId = "TKT007",
                            CheckInTime = new DateTime(2026, 5, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutTime = new DateTime(2026, 5, 9, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Fee = 24000m,
                            SlotId = "B03",
                            Status = "Đã ra",
                            VehiclePlate = "74A-567.89",
                            VehicleType = "Ô tô nhỏ"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Vehicle", b =>
                {
                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VehiclePlate");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicle_Type", "VehicleType IN (N'Xe máy', N'Ô tô nhỏ', N'Ô tô lớn')");
                        });

                    b.HasData(
                        new
                        {
                            VehiclePlate = "43A-123.45",
                            CustomerId = "CUS001",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            VehiclePlate = "43B-456.78",
                            CustomerId = "CUS002",
                            VehicleType = "Ô tô nhỏ"
                        },
                        new
                        {
                            VehiclePlate = "43C-789.01",
                            CustomerId = "CUS003",
                            VehicleType = "Xe máy"
                        },
                        new
                        {
                            VehiclePlate = "43D-234.56",
                            CustomerId = "CUS004",
                            VehicleType = "Ô tô lớn"
                        },
                        new
                        {
                            VehiclePlate = "51G-888.88",
                            CustomerId = "CUS001",
                            VehicleType = "Ô tô nhỏ"
                        });
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Customer", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("ParkingManagement.DAL.Models.Customer", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Employee", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Account", "Account")
                        .WithOne("Employee")
                        .HasForeignKey("ParkingManagement.DAL.Models.Employee", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingManagement.DAL.Models.Manager", "Manager")
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Manager", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Account", "Account")
                        .WithOne("Manager")
                        .HasForeignKey("ParkingManagement.DAL.Models.Manager", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.MonthlyTicket", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingManagement.DAL.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehiclePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.ParkingSlotAuditLog", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingManagement.DAL.Models.ParkingSlot", "ParkingSlot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ParkingSlot");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Payment", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.MonthlyTicket", "MonthlyTicket")
                        .WithOne("Payment")
                        .HasForeignKey("ParkingManagement.DAL.Models.Payment", "MonthlyTicketId");

                    b.HasOne("ParkingManagement.DAL.Models.Ticket", "Ticket")
                        .WithOne("Payment")
                        .HasForeignKey("ParkingManagement.DAL.Models.Payment", "TicketId");

                    b.Navigation("MonthlyTicket");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Reservation", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingManagement.DAL.Models.ParkingSlot", "ParkingSlot")
                        .WithMany("Reservations")
                        .HasForeignKey("SlotId");

                    b.HasOne("ParkingManagement.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Reservations")
                        .HasForeignKey("VehiclePlate");

                    b.Navigation("Customer");

                    b.Navigation("ParkingSlot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Ticket", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId");

                    b.HasOne("ParkingManagement.DAL.Models.ParkingSlot", "ParkingSlot")
                        .WithMany("Tickets")
                        .HasForeignKey("SlotId");

                    b.HasOne("ParkingManagement.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Tickets")
                        .HasForeignKey("VehiclePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ParkingSlot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Vehicle", b =>
                {
                    b.HasOne("ParkingManagement.DAL.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Account", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Customer", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Tickets");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Manager", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.MonthlyTicket", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.ParkingSlot", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Ticket", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ParkingManagement.DAL.Models.Vehicle", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
